- name: Generate manpages
  shell: bash
  run: |
    set -euo pipefail
    out_dir="dist/share/man/man1"
    mkdir -p "$out_dir"
    if [ "$RUNNER_OS" != "Windows" ]; then
      cargo run --package xtask -- man --out-dir "$out_dir"
    fi
